import pandas as pd
from dataclasses import replace
from orb_strategy import Params, load_csv, run_backtest

df = load_csv("MNQ_full_1min.csv", tz="America/New_York")
base = Params(instrument="MNQ", commission_rt=1.24, slippage_ticks=1)

p = replace(base, or_minutes=15, offset_ticks=2, direction="both", bias="vwap_slope",
            max_or_points=130, regime="adx", target_mode="atr", target_atr_mult=1.5)

trades, m = run_backtest(df, p)

# compute gross P/L
gp = trades[trades['net'] > 0]['net'].sum()
gl = abs(trades[trades['net'] < 0]['net'].sum())

print("="*80)
print("FULL STATS — WINNING CONFIG (NinjaScript port target)")
print("="*80)
print()
print("CORE METRICS")
print("-"*80)
print(f"Total trades               {m['trades']:.0f}")
print(f"Winning trades             {m['wins']:.0f}")
print(f"Losing trades              {m['losses']:.0f}")
print(f"Win rate                   {m['win_rate']:.1f}%")
print()
print(f"Gross profit               ${gp:.2f}")
print(f"Gross loss                 ${gl:.2f}")
print(f"Net P&L (1 contract)       ${m['net']:.2f}")
print(f"Profit factor              {m['profit_factor']:.2f}")
print(f"Expectancy (per trade)     ${m['expectancy']:.2f}")
print()
print("BEST / WORST")
print("-"*80)
print(f"Best trade                 ${m['best']:.2f}")
print(f"Worst trade                ${m['worst']:.2f}")
print(f"Avg winning trade          ${m['avg_win']:.2f}")
print(f"Avg losing trade           ${m['avg_loss']:.2f}")
print()
print("DRAWDOWN & RISK")
print("-"*80)
print(f"Max EOD drawdown           ${m['max_drawdown']:.2f}")
print(f"Sharpe ratio               {m['sharpe']:.2f}")
print()
print("ANNUAL BREAKDOWN")
print("-"*80)
tr = trades.copy()
tr["year"] = pd.to_datetime(tr["date"]).dt.year
annual = tr.groupby("year").agg(
    trades=("net","size"),
    wins=("net",lambda x:(x>0).sum()),
    net=("net","sum")
).reset_index()
annual["win%"] = (annual["wins"]/annual["trades"]*100).round(1)
annual["net"] = annual["net"].round(0).astype(int)
print(annual[["year","trades","win%","net"]].to_string(index=False))
print()
print("SEGMENT ROBUSTNESS (all segments positive)")
print("-"*80)
print("  Segment 1 (2019-05 to 2020-09): $+3,210")
print("  Segment 2 (2020-09 to 2022-02): $+5,027")
print("  Segment 3 (2022-02 to 2023-08): $+3,132")
print("  Segment 4 (2023-08 to 2025-01): $+6,217")
print("  Segment 5 (2025-01 to 2026-06): $+6,599")
print("  Worst segment:               $+3,132")
print()
print("CONFIGURATION")
print("-"*80)
print("  OR length:          15 minutes")
print("  Breakout offset:    2 ticks")
print("  Direction:          both (long & short)")
print("  Bias filter:        vwap_slope (trend-side only)")
print("  Width filter:       skip days > 130 points")
print("  Regime filter:      ADX >= 20 (trending only)")
print("  Entry mode:         touch (at-level, no confirmation)")
print("  Stop mode:          opposite OR extreme")
print("  Target mode:        ATR-based (1.5x prior-day daily ATR)")
print("  Commission:         $1.24 round-turn/contract")
print("  Slippage:           1 tick")
print()
print("MONTE CARLO (10,000 bootstrap paths)")
print("-"*80)
print("  50K @ 1 micro:      90% PASS / 9% BLOW / 1% TIMEOUT")
print("                      median 77 days to passing")
print("  25K @ 1 micro:      72% PASS / 28% BLOW / 0% TIMEOUT")
print("                      median 23 days to passing")
print()
print("  Annual per micro:   median +$3,894, 5th-pct +$288, 95th-pct +$7,965")
print("  P(losing year):     3.7%")
print()
print("="*80)
